### ISSUE TITLE
Finish and test localization

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#14]
While there is great support in DialogOS for localizing all strings in the GUI, not all strings are currently localized. Before the first release, all strings should be localized at least to English (= default) and German. 

This needs to be tested on a variety of machines with different OSs and language settings. Currently I think locales on MacOS are a bit weird. If one is specified on the command line using LC_ALL, it is at some point overwritten by DialogOS.

**Comment by alexanderkoller** [comment]
Maybe this will help: https://phraseapp.com/

There is a configuration file for PhraseApp in the root directory of the DialogOS source tree. It is probably out of date, but could be updated and then the translations put in.

**Comment by akoehn** [comment]
The phraseapp configuration is up to date, the complete I18n infrastructure was revamped during our project.  I'll make sure to obtain a good documentation for using phraseapp.

**Comment by alexanderkoller** [comment]
Do we have to configure modules that contain localized strings by hand, or will phraseapp pick them all up automatically? I created a couple of new plugins and refactored others, that's why I was uncertain.

**Comment by alexanderkoller** [comment]
Keeping track of our progress [here](https://github.com/coli-saar/dialogos/wiki/Cleanup-work).

**Comment by alexanderkoller** [comment]
We should also make sure that all code uses localized strings, instead of bare string literals.

**Comment by timobaumann** [comment]
all resource bundles have both .properties and .properties_en. 
Isn't en the default?

**Comment by alexanderkoller** [comment]
@timobaumann This is now done, except for the localization in the NXT and Pocketsphinx plugins. Do I have write access to the repositories where you moved them? Could you move them to a `dialogos-project` organization as we discussed? Or could you finish the checking in these modules yourself?

**Comment by alexanderkoller** [comment]
Localized strings in DialogOS and the NXT plugin should now be synchronized between English and German.

It may be worth going through all ~5000 literal strings in the code and localize them if necessary. This seems less urgent, and I've opened issue #78 (not in Milestone 2.0) for it.

**Comment by alexanderkoller** [comment]
PS Localization of the PocketSphinx plugin is no longer needed, because we no longer use that plugin.
