### ISSUE TITLE
Replace JRendezvous.jar

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#16]
libs/JRendezvous.jar is a leftover Jar file from the old DialogOS. It seems to be an old version of [jmDNS](https://github.com/jmdns/jmdns), which is under active development and [available from Maven Central](https://mvnrepository.com/artifact/org.jmdns/jmdns).

We should replace the old Jar file with a proper dependency to the Maven Central version. This needs to be tested carefully, with a test client, to make sure nothing broke in the conversion.

**Comment by akoehn** [comment]
IIRC, the new version from maven central was not API-compatible with the current DialogOS, i.e. there would need to be some refactoring.  Otherwise it would have been already replaced.

**Comment by alexanderkoller** [comment]
Done in https://github.com/coli-saar/dialogos/commit/7de8dd261ab0f702e3638c73460008198a43de60.
