### ISSUE TITLE
DynamicGrammars

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#21]
In addition to real grammars and DirectGrammars (which only do keyword spotting), DialogOS recognizer nodes also support DynamicGrammars. However, in contrast to what the documentation suggests, these do not allow placeholders or regular expressions. Find out what's going on and document it.

**Comment by timobaumann** [comment]
dynamic grammars are computed from a script language expression. This may have to be documented, but somehow this has always been clear to me. 
Where are dynamic grammars referenced in the documentation?

**Comment by timobaumann** [comment]
I have added a few remarks to the Wiki.
