### ISSUE TITLE
Nodes should be filled correctly on Linux

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#36]
On Ubuntu 16.04 using Ubuntu Desktop, nodes are not always filled correctly. This looks ugly and makes the node labels hard to read. Find out why, and fix it.

![nodes](https://user-images.githubusercontent.com/8291392/35907977-b6a677fa-0bef-11e8-9f01-fe9bf1ebe884.png)

**Comment by timobaumann** [comment]
the cause is 
```java
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
```
in DialogOS.java:>277 which is resolved to com.sun.java.swing.plaf.gtk.GTKLookAndFeel 
Same for alignment of labels in panel in #35 

We may have to override these peculiarities of GTKLookAndFeel -- or just ditch styling alltogether and admit to being a swing application...

**Comment by timobaumann** [comment]
it does not look like Oracle cares about this: https://bugs.java.com/view_bug.do?bug_id=6531760
