### ISSUE TITLE
Install recognizer models when DialogOS is first run

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#49]
When DialogOS is started on a computer for the first time (i.e. the ~/.dialogos directory does not exist yet), we should show a dialogue that offers recognizer models for the default recognizer for download.

**Comment by timobaumann** [comment]
obviously also depends on #15

**Comment by akoehn** [comment]
This can already be done in the installer (#4).

**Comment by timobaumann** [comment]
we decided yesterday to do this in the installer.
