### ISSUE TITLE
Fix size of canvas at startup

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#51]
It is currently smaller than the window size, and the borders are visible.

**Comment by timobaumann** [comment]
if you close the left subgraph menu, then it's not too wide anymore. 
if there were fewer node types (or you use the grouping node display and close a few groups) then it's the right height.

**Comment by alexanderkoller** [comment]
This seems to work on MacOS now. Need to test on Windows and Linux.

**Comment by timobaumann** [comment]
works on Linux as well.

**Comment by alexanderkoller** [comment]
@timobaumann When you say "works", do you mean that (a) the canvas has exactly the right size at startup (no black line for the border of the canvas visible inside the scrollbars) and (b) the canvas resizes precisely when you drag the window bigger? Could you post a screenshot of the freshly started DialogOS?

On my Linux, the canvas is a few pixels too small in the Y direction at startup, and when the window is resized, the border between canvas and scrollbars grows further and then stays the same size.

On Windows 10, the canvas is a few pixels too wide in the X direction at startup, and is then resized correctly when the window is made larger. This is probably because the separator between the subgraph panel and the canvas is less wide on Windows than on MacOS.

**Comment by alexanderkoller** [comment]
This mostly works now. On MacOS, it seems fine; on my Windows, the graph is a tiny bit too tall, and on my Ubuntu, the graph is a tiny bit too wide. Let's call it good enough for the release.
