### ISSUE TITLE
SphinxNodeTest fails unless you speak to it.

### ISSUE THREAD

**Issue by akoehn** [coli-saar/dialogos#53]
On a fresh clone of master, ```./gradlew test``` results in this:
```
com.clt.speech.recognition.SphinxTest > testSpeechRecognitionFunctionality FAILED
    java.lang.AssertionError at SphinxTest.java:151
```

Timo, does it work for you?

**Comment by timobaumann** [comment]
fails differently for me but that's not reassuring either.

**Comment by timobaumann** [comment]
fails differently for me but that's not reassuring either.

**Comment by timobaumann** [comment]
SphinxTest works well with a clean checkout for me. Also, SphinxTest does not have an assertion in line SphinxNodeTest fails for me, however. (Although the application works fine.)

**Comment by timobaumann** [comment]
@akoehn can you reconfirm that on e4097d4 you have trouble running :SphinxClient:test ? Because this works nicely for me (whereas SphinxNodeTest runs into some sort of Swing/XWait problems.)

**Comment by timobaumann** [comment]
SphinxTest is working fine but SphinxNodeTest still assumes that you speak a digit (0-9 in english) during testing at the right point in time. This still needs fixing.

**Comment by timobaumann** [comment]
I'm removing the sphinx4 tag is this will similarly bite other tests.

**Comment by akoehn** [comment]
I still have this isssue on a freshly checked out master branch.  `./gradlew build` yields this:
```> Task :plugins:DialogOS_SphinxPlugin:test 

edu.cmu.lti.dialogos.sphinx.client.SphinxTest > testSpeechRecognitionFunctionality FAILED
    java.lang.AssertionError at SphinxTest.java:152

edu.cmu.lti.dialogos.sphinx.client.SphinxTest > grammarRecognitionTest FAILED
    java.lang.AssertionError at SphinxTest.java:170

11 tests completed, 2 failed, 2 skipped
```

**Comment by akoehn** [comment]
``

**Comment by akoehn** [comment]
I replicated this on a different system (rzssh1 @ inf uni hamburg) 
@timobaumann you can have a look at it here: /home/scratch/koehn/dialogos

**Comment by timobaumann** [comment]
related to https://github.com/cmusphinx/sphinx4/issues/76 ; fix to that was commited to sphinx/master in november, maybe it's still not in the SNAPSHOT.jar?

**Comment by timobaumann** [comment]
the snapshot on sonatype.org is from 2016 :-/ and my local maven cache contained the fix :-\
jitpack.io to the rescue, once again. 
fixed in 9d368ef, could you check and close (if it's fixed)?

**Comment by timobaumann** [comment]
also: thanks for making the stacktrace available which helped me find the problem very quickly.

**Comment by timobaumann** [comment]
I heard from Arne that this works now, so closing. Please reopen if still
