### ISSUE TITLE
Convert legacy XML into modern format

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#56]
- Class names used to be only the class, now include package name.
- Some old classes no longer exist (e.g. VoconNode) and need to be replaced by Sphinx nodes.

**Comment by timobaumann** [comment]
Added backwards compatibility in d40d3c6 . Please try with a few files that you still have lying around from old DialogOS.

This casts the prior TTSNode to Mary's TTSNode and the prior commercial-ASR node to SphinxNode (Sphinx-4). If these are not available, then we fail.

Also, there are no attempts to change the voice names (for Mary) or potential ASR configurations. These have to be changed manually (or MaryNode should be changed to switch to default voice if the requested voice is unavailable).

Finally, I did not bother to attempt to display a warning message. This would potentially have to be done via a much-extended ProgressDialog and I simply don't care enough about people that are confused from using mixed environments of old/new DialogOS.
