### ISSUE TITLE
add icon to main dialogos windows

### ISSUE THREAD

**Issue by timobaumann** [coli-saar/dialogos#74]
the new/load file window and the documentviewer window.
easy to do: https://stackoverflow.com/questions/15657569/how-to-set-icon-to-jframe?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
use the AppIconLarge.png in main/resources/images/

**Comment by alexanderkoller** [comment]
Is this a thing that needs to happen for 2.0, or can it happen after the release?

If it's a quick fix, do you want to assign the issue to yourself and do it?

**Comment by alexanderkoller** [comment]
I think there used to be an actual logo for DialogOS, see e.g. here https://en.wikipedia.org/wiki/DialogOS

I have put that file (it is CC BY-SA) in Diamant/src/main/resources/images/logo and also made a cropped version that only has the image and not the text. We should probably make a clean version of the image at some point (it is a JPG), but it seems better for an icon than the bigger image you linked to.

**Comment by timobaumann** [comment]
fixed in eb35251. we will need something with higher contrast than the current icon.
