### ISSUE TITLE
Diamant is leaking JUnit 4.10 as a transitive dependency

### ISSUE THREAD

**Issue by errantlinguist** [coli-saar/dialogos#75]
As of 2018-06-1 with commit 700921a5af of DialogOS (which uses Diamant commit 700921a5af), JUnit 4.10 is leaked to the `compile` configuration (note: *not* `testCompile`) for software which depends on DialogOS. This breaks compilation for tests that use 4.12 due to e.g. additional methods in the latter:

    ./gradlew dependencyInsight --configuration compile --dependency junit
    Parallel execution is an incubating feature.

    > Task :dependencyInsight
	junit:junit:4.10
	   variant "runtime" [
		  Requested attributes not found in the selected variant:
		     org.gradle.usage = java-api
	   ]
	\--- com.googlecode.json-simple:json-simple:1.1.1
		 \--- com.github.coli-saar.dialogos:Diamant:master-SNAPSHOT:700921a5af-1
		      +--- com.github.coli-saar:dialogos:master-SNAPSHOT:700921a5af-1

When built using the Gradle wrapper `./gradlew build`, there is no issue. However, when building through Eclipse using Eclipse's Gradle plugin, the version from `compile` takes precedence over `testCompile`.

**Build environment:**

- Gradle wrapper 4.7
- openjdk build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
- Linux kernel 4.13.0-43-generic (Linux Mint 18.3 Sylvia)
- Eclipse IDE for Java Developers
    - Version: Oxygen.3a Release (4.7.3a)
    - Build id: 20180405-1200
    - OS: Linux, v.4.13.0-43-generic, x86_64 / gtk 3.18.9, WebKit 2.4.11
- Eclipse Gradle plugin ("buildship") 2.2.1.v20180125-1441

**Comment by timobaumann** [comment]
hm. so it's actually json-simple that is leaking the dependency. 
I think this bug is somewhere between json-simple (unmaintained) and eclipse (hard to negotiate with). Thus I'm marking this as wontfix. 
However, I opened #76 because we really should not be using two JSON libraries and json-simple is probably the right one to go.

**Comment by timobaumann** [comment]
fixed by #76.
