### ISSUE TITLE
Sphinx recognition of capitalized and unknown words

### ISSUE THREAD

**Issue by akoehn** [coli-saar/dialogos#77]
It seems to me that capitalized words are currently not recognized:
```
INFORMATION: The dictionary is missing a phonetic transcription for the word 'Uhr'
```
lowercased recognition works just fine.  I don't know whether this should be added to the documentation or it should be fixed somewhere.

In addition, does sphinx currently recognize words not in the dictionary?  I tried to evaluate that but the current environment is too noisy.

**Comment by alexanderkoller** [comment]
I thought about that too, but it seems like a potentially risky fix if you don't distinguish between terminals and nonterminals. The case may be the only thing that distinguishes them, so if you make the nonterminal lowercase you may obliterate the difference. Can we convert only all the terminal symbols to lowercase?

**Comment by timobaumann** [comment]
it's happening in the dictionary, so no worries about non-terminals. see 88cf730.
fun fact: German dictionary is all lowercase, CMUDict ist all uppercase. go figure...
