### ISSUE TITLE
Replace copyright notices in source code

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#8]
All copyright notices in the source code should be changed from CLT + proprietary license to Uni Saarland + Apache license. These licences should also be added to all files that don't have them yet.

**Comment by akoehn** [comment]
Do you want Apache or GPL? The dirty-dialogos had GPLv3 as a license.  Changing the license to Apache means we have to check all libraries for compatibility and I would ask all contributors whether they are okay with licensing their work under Apache.

**Comment by alexanderkoller** [comment]
I don't know if I care strongly one way or another. When I looked at Apache vs. GPL, it seemed to me that Apache was less restrictive, and I don't mind commercial use of DialogOS. Would you prefer GPL?

Apparently there is [a Gradle plugin](https://github.com/hierynomus/license-gradle-plugin) that can list the licenses of included Maven dependencies. Perhaps we can check whether we are including a dependency that is incompatible with Apache. What happens if we license our own source code under Apache, but our binary distribution contains non-Apache libraries?

**Comment by akoehn** [comment]
I asked our students and so far everyone agreed to use apache2.
