### ISSUE TITLE
Copyright notices in GUI

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#9]
The GUI displays the CLT logo in many places. Replace it by the Saarland Owl, or add the Owl everywhere the CLT logo appears. Change the copyright notices in the GUI in all appropriate places. Make sure to acknowledge the Hamburg students who helped move DialogOS into open-source.

**Comment by alexanderkoller** [comment]
Also, PocketSphinx and MaryTTS and their copyright holders should be acknowledged in the GUI.

**Comment by akoehn** [comment]
For reference: the students involved in our project are listed here:
https://dialogossose17.github.io/credits.html

**Comment by alexanderkoller** [comment]
Done.
